version: '2'
services:
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend
    tty: true
    stdin_open: true
    networks: 
      - backend
  backend:
    build: ./server
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    networks: 
      - backend
  mongo:
    image: mongo
    container_name: puppypals-mongodb
    ports:
      - "27017:27017" 

networks:
  backend:
    driver: bridge